config/routes.rb
LeadApp::Application.routes.draw do  

  mount Messaging::Engine => "/messaging"

  devise_for :messaging_users

  get "static_pages/home"

  get "static_pages/help"

  resources :quotes do
    member do
      get :vendors
    end
  end

  resources :relationships, only: [:create, :destroy]

  devise_for :vendors, path_names: {sign_up: "signup", sign_in: "login", sign_out: "logout"}
  resources :vendors, only: [:index, :show] do
    member do
      get :quotes
    end
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

    root to: 'static_pages#home'

end

app/models/messaging_user.rb
class MessagingUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  include Mailboxer::Models::Messageable
  acts_as_messageable

  def name
    self.to_s
  end

  def mailboxer_email(message)
    email
  end

  def to_s
    email
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :budget, :comments, :event_date, :event_time, :quote_type, :solicitation_type, :wedding_style, :zip_code
  
  belongs_to :user

	has_many :reverse_relationships, foreign_key: "quote_id", class_name: "Relationship", dependent: :destroy
	has_many :vendors, through: :reverse_relationships, source: :vendor


end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :quote_id

  belongs_to :quote
	belongs_to :vendor

  	validates :vendor_id, presence: true
  	validates :quote_id, presence: true

end

app/models/relationships.rb
class Relationships < ActiveRecord::Base
  attr_accessible :quote_id, :vendor_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :quotes
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :relationships, foreign_key: "vendor_id", dependent: :destroy 
    has_many :quotes, through: :relationships, source: "quote_id"

  acts_as_messageable

	def bidding?(quote)
    	relationships.find_by_quote_id(quote.id)
    end

    def bid!(quote)
    	relationships.create!(quote_id: quote.id)
    end         

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
   before_filter :authenticate_vendor!
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quotes }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @quote = Quote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(params[:quote])

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render json: @quote, status: :created, location: @quote }
      else
        format.html { render action: "new" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])

    respond_to do |format|
      if @quote.update_attributes(params[:quote])
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_filter :authenticate_vendor!

	def create
		@quote = Quote.find(params[:relationship][:quote_id])
		current_vendor.bid!(@quote)
		redirect_to @quote
	end		
end
	

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
     <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Bride Bidder"%></a></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <li>
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path %> 
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            <% else %>
              <% if vendor_signed_in? %>
              Logged in as <strong><%= current_vendor.email %></strong>.
              
              <%= link_to 'Edit profile', edit_vendor_registration_path %> 
              <%= link_to "Logout", destroy_vendor_session_path, method: :delete %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path %> 
              <li class="divider"></li>
              <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
            <% end %>
          </li>
          <li class="divider"></li>
          <li><%= link_to "List Your Service", "static_pages/vendors" %></li>
        </ul>
      </div>
    </nav>


    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
  <dl class="sub-nav">
  <dt>Test:</dt>
  <dd class="active"><a href="#">All</a></dd>
  
</dl>
</html>

app/views/quotes/_bid.html.erb
<%= form_for(current_vendor.relationships.build(quote_id: @quote.id)) do |f| %>
	<div><%= f.hidden_field :quote_id %></div>
	<%= f.submit "Submit Bid", class: "tiny button" %>
<% end %>

app/views/quotes/_form.html.erb
<div class="row">
  <div class="large-4 large-8 columns">

<%= simple_form_for(@quote) do |f| %>
  <%= f.error_notification %>
  <%= f.input :quote_type %>
  <%= f.input :wedding_style, collection: ["Ceremony Photos", "Reception Photos", "Ceremony Preparation", "Engagement Photos", "Family Photos", "Not Sure Yet", "Other"], as: :radio %>
  <%= f.input :budget, collection: ["Less than $500", "$500-1000", "$1000+"] %>
  <%= f.input :comments %>
  <%= f.input :event_date %>
  <%= f.input :event_time %>
  <%= f.input :zip_code %>
  <%= f.input :solicitation_type %>
    <%= f.error :base %>
    <%= f.button :submit %>
  </div>
<% end %>
</div>
</div>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<h1>Listing quotes</h1>

<table>
  <tr>
    <th>Quote type</th>
    <th>Wedding style</th>
    <th>Budget</th>
    <th>Comments</th>
    <th>Event date</th>
    <th>Event time</th>
    <th>Zip code</th>
    <th>Solicitation type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quotes.each do |quote| %>
  <tr>
    <td><%= quote.quote_type %></td>
    <td><%= quote.wedding_style %></td>
    <td><%= quote.budget %></td>
    <td><%= quote.comments %></td>
    <td><%= quote.event_date %></td>
    <td><%= quote.event_time %></td>
    <td><%= quote.zip_code %></td>
    <td><%= quote.solicitation_type %></td>
    <td><%= link_to 'Show', quote %></td>
    <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
    <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote type:</strong>
  <%= @quote.quote_type %>
</p>

<p>
  <strong>Wedding style:</strong>
  <%= @quote.wedding_style %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @quote.budget %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @quote.comments %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @quote.event_date %>
</p>

<p>
  <strong>Event time:</strong>
  <%= @quote.event_time %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @quote.zip_code %>
</p>

<p>
  <strong>Solicitation type:</strong>
  <%= @quote.solicitation_type %>
</p>

<%= render 'bid' if vendor_signed_in? %>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="large-9 large-8 columns">

		<h1>Bride Bidder</h1>
		<p>Find me in app/views/static_pages/home.html.erb</p>
		<a href="/quotes/new" class="large button">Get a Quote</a>
	</div>
</div>